[package]
name = "matecito-dll"
version = "0.1.0"
authors = ["Blas Rodriguez Irizar <blas@layertwo.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
matecito = []